package edu.grinnell.csc207.soundsofsorting;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.events.*;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length - i - 1; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<>(j, j + 1));
                    swap(arr, j, j + 1);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            int minIndex = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, minIndex));
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }
            events.add(new SwapEvent<>(i, minIndex));
            swap(arr, i, minIndex);
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            T compared = arr[i];
            int j = i - 1;
            events.add(new CompareEvent<>(j, i));
            while (j >= 0 && arr[j].compareTo(compared) > 0) {
                events.add(new CopyEvent<>(j + 1, arr[j]));
                arr[j + 1] = arr[j];
                j--;
            }
            events.add(new CopyEvent<>(j + 1, compared));
            arr[j + 1] = compared;

        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        mergeSortHelper(arr, 0, arr.length, events);
        return events;
    }

    /**
     * Recursive helper function for merge sort.
     *
     * @param <T>       the carrier type of the array
     * @param arr       the array to sort
     * @param firstIdx  the lower bound of the subarray
     * @param secondIdx the upper bound of the subarray
     * @param events    the list of sort events
     */
    public static <T extends Comparable<? super T>> void mergeSortHelper(
            T[] arr, int firstIdx, int secondIdx, List<SortEvent<T>> events) {
        if (secondIdx - firstIdx <= 1) {
            return;
        }
        int middle = firstIdx + (secondIdx - firstIdx) / 2;
        mergeSortHelper(arr, firstIdx, middle, events);
        mergeSortHelper(arr, middle, secondIdx, events);
        merge(arr, firstIdx, middle, secondIdx, events);
    }

    /**
     * Merging helper function for merge sort algorithm.
     * Merges the two sorted halves into a sorted whole.
     *
     * @param <T>    the carrier type of the array
     * @param arr    the array to merge into
     * @param lo     the lower bound of the left half (inclusive)
     * @param mid    the upper bound of the left half (exclusive)
     * @param hi     the upper bound of the right half (exclusive)
     * @param events the list of sort events
     */
    public static <T extends Comparable<? super T>> void merge(T[] arr, int firstIdx, int middle, int secondIdx,
            List<SortEvent<T>> events) {
        // lengths or arrays
        T[] leftArr = Arrays.copyOfRange(arr, firstIdx, middle);
        T[] rightArr = Arrays.copyOfRange(arr, middle, secondIdx);

        // indeces to walk over the arrays
        int idxLeft = 0;
        int idxRight = 0;
        int idxArr = firstIdx;

        while (idxLeft < leftArr.length && idxRight < rightArr.length) {
            events.add(new CompareEvent<>(firstIdx + idxLeft, middle + idxRight));
            if (leftArr[idxLeft].compareTo(rightArr[idxRight]) < 0) {
                events.add(new CopyEvent<>(idxArr, leftArr[idxLeft]));
                arr[idxArr] = leftArr[idxLeft];
                idxArr++;
                idxLeft++;
            } else {
                events.add(new CopyEvent<>(idxArr, rightArr[idxRight]));
                arr[idxArr] = rightArr[idxRight];
                idxArr++;
                idxRight++;
            }
        }

        // if any elements left in the left array
        while (idxLeft < leftArr.length) {
            events.add(new CopyEvent<>(idxArr, leftArr[idxLeft]));
            arr[idxArr] = leftArr[idxLeft];
            idxArr++;
            idxLeft++;
        }

        // if any elements left in the right array
        while (idxRight < rightArr.length) {
            events.add(new CopyEvent<>(idxArr, rightArr[idxRight]));
            arr[idxArr] = rightArr[idxRight];
            idxArr++;
            idxRight++;
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        quickSortHelper(arr, 0, arr.length - 1, events);

        return events;

    }

    public static <T extends Comparable<? super T>> void quickSortHelper(T[] arr, int low, int high,
            List<SortEvent<T>> events) {
        if (low < high) {
            int pivotIndex = partition(arr, low, high, events);
            quickSortHelper(arr, low, pivotIndex - 1, events);
            quickSortHelper(arr, pivotIndex + 1, high, events);
        }
    }

    public static <T extends Comparable<? super T>> int partition(T[] arr, int low, int high,
            List<SortEvent<T>> events) {
        T pivot = arr[high];
        int i = low - 1;

        for (int j = low; j < high; j++) {
            events.add(new CompareEvent<>(j, high));
            if (arr[j].compareTo(pivot) < 0) {
                i++;
                events.add(new SwapEvent<>(i, j));
                swap(arr, i, j);
            }
        }
        events.add(new SwapEvent<>(i + 1, high));
        swap(arr, i + 1, high);
        return i + 1;
    }

    /**
     * Sorts the given array by applying the given events to it, in sequence.
     * 
     * @param events the sorting events to apply
     * @param arr    the array to sort
     */
    public static <T extends Comparable<? super T>> void eventSort(
            List<SortEvent<T>> events, T[] arr) {
        for (SortEvent<T> event : events) {
            event.apply(arr);
        }
    }
}
