package edu.grinnell.csc207.soundsofsorting;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.events.*;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i   the first index to swap
     * @param j   the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * 
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length - i - 1; j++) {
                events.add(new CompareEvent<>(j, j + 1));
                if (arr[j].compareTo(arr[j + 1]) > 0) {
                    events.add(new SwapEvent<>(j, j + 1));
                    swap(arr, j, j + 1);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * 
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            int minIndex = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, minIndex));
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }
            events.add(new SwapEvent<>(i, minIndex));
            swap(arr, i, minIndex);
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * 
     * <pre>
     * [ i elements in order | unprocessed ]
     * </pre>
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int i = 1; i < arr.length; i++) {
            T compared = arr[i];
            int j = i - 1;
            events.add(new CompareEvent<>(j, i));
            while (j >= 0 && arr[j].compareTo(compared) > 0) {
                events.add(new CopyEvent<>(j + 1, arr[j]));
                arr[j + 1] = arr[j];
                j--;
            }
            events.add(new CopyEvent<>(j + 1, compared));
            arr[j + 1] = compared;

        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
         int len = arr.length;
        if (len <= 1) {
            return events;
        }
        int middle = len / 2;
        T[] leftArr = Arrays.copyOfRange(arr, 0, middle);
        T[] rightArr = Arrays.copyOfRange(arr, middle, len);
        int rightPointer = 0;
        for (int i = 0; i < len; i++) {
            if (i < middle) {
                leftArr[i] = arr[i];
            } else {
                rightArr[rightPointer] = arr[i];
                rightPointer++;
            }
        }
        mergeSort(leftArr);
        mergeSort(rightArr);
        merge(arr, leftArr, rightArr, events);
        return events;
    }

    /**
     * Helper for merge sort algorithm:
     * Merges the two sorted halves into a sorted whole.
     *
     * @param <T>      the carrier type of the array
     * @param arr      the array to merge into
     * @param leftArr  the sorted left half
     * @param rightArr the sorted right half
     */
    public static <T extends Comparable<? super T>> void merge(T[] arr, T[] leftArr, T[] rightArr, List<SortEvent<T>> events) {
        // lengths or arrays
        int leftLen = leftArr.length;
        int rightLen = rightArr.length;

        // indeces to walk over the arrays
        int idxLeft = 0;
        int idxRight = 0;
        int idxArr = 0;

        while (idxLeft < leftLen && idxRight < rightLen) {
            if (leftArr[idxLeft].compareTo(rightArr[idxRight]) < 0) {
                events.add(new CopyEvent<>(idxArr, leftArr[idxLeft]));
                arr[idxArr] = leftArr[idxLeft];
                idxArr++;
                idxLeft++;
            } else {
                events.add(new CopyEvent<>(idxArr, rightArr[idxLeft]));
                arr[idxArr] = rightArr[idxRight];
                idxArr++;
                idxRight++;
            }
        }

        // if any elements left in the left array
        while (idxLeft < leftLen) {
            events.add(new CopyEvent<>(idxArr, leftArr[idxLeft]));
            arr[idxArr] = leftArr[idxLeft];
            idxArr++;
            idxLeft++;
        }

        // if any elements left in the right array
        while (idxRight < rightLen) {
            events.add(new CopyEvent<>(idxArr, rightArr[idxLeft]));
            arr[idxArr] = rightArr[idxRight];
            idxArr++;
            idxRight++;
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * 
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        // TODO: fill me in!
        return events;
    }

    /**
     * Sorts the given array by applying the given events to it, in sequence.
     * 
     * @param events the sorting events to apply
     * @param arr    the array to sort
     */
    public static <T extends Comparable<? super T>> void eventSort(
            List<SortEvent<T>> events, T[] arr) {
        // TODO: implement me!
    }
}
